src/sc_auth/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import LogoutView

from sc_auth.views import LoginView, SignUpView


urlpatterns = [
    url(r'^login', LoginView.as_view(), name='login'),
    url(r'^sign_up$', SignUpView.as_view(), name='sign_up'),
    url(r'^logout', LogoutView.as_view(), name='logout'),
]

src/sc_server/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cms.urls')),
    url(r'^auth/', include(('sc_auth.urls', 'sc_auth'), namespace="sc_auth")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# urlpatterns = [
#     path(r'admin/', admin.site.urls),
#     path(r'', include('cms.urls')),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

src/sc_auth/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class CustomUser(AbstractUser):
    subscriptions = models.ManyToManyField("sc_clubs.SportClub", verbose_name=_("subscriptions"), blank=True,
                                           through="UserClubSubscription")
    phone_number = PhoneNumberField(verbose_name=_("Номер телефону"))

    class Meta:
        verbose_name = _("Користувач")
        verbose_name_plural = _("Користувачi")

    def __str__(self):
        return self.username + " %s (%s - %s)" % (self.get_full_name(), self.email, self.phone_number)


class UserClubSubscription(models.Model):
    sportclub = models.ForeignKey("sc_clubs.SportClub", on_delete=models.CASCADE, verbose_name="Секція")
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Користувач")
    comment = models.TextField(max_length=256, editable=False, null=True, blank=True, verbose_name=_("Коментарій"))

    created_at = models.DateTimeField(auto_now_add=True)
    is_processed = models.BooleanField(default=False, verbose_name=_("Оброблено"))

    class Meta:
        unique_together = ("sportclub", "user")
        verbose_name = _("Пiдписник")
        verbose_name_plural = _("Пiдписники")

    def __str__(self):
        return "%s  - %s" % (self.sportclub.name, self.user)

src/sc_auth/forms.py
from django import forms

from django.core.validators import validate_email
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.utils.translation import ugettext as _
from phonenumber_field.widgets import PhoneNumberPrefixWidget

from sc_core.utils import validate_password
from phonenumber_field.validators import validate_international_phonenumber


class LoginForm(forms.Form):
    login_username = forms.CharField(max_length=32, required=True,
                                     widget=forms.TextInput(attrs={'placeholder': _('Нікнейм')}), label=False)
    login_password = forms.CharField(max_length=32, required=True,
                                     widget=forms.PasswordInput(attrs={'placeholder': _('Пароль')}), label=False)

    def clean(self):
        form_data = self.cleaned_data
        login_username = self.cleaned_data.get("login_username")
        if login_username:
            ASCIIUsernameValidator()(login_username)
        if not self.cleaned_data.get('login_username', None):
            self._errors["login_username"] = self.error_class(self._errors["login_username"])
        return form_data


class SignUpForm(forms.Form):
    signup_username = forms.CharField(max_length=32, required=True,
                                      widget=forms.TextInput(
                                          attrs={'placeholder': _('Нікнейм'), 'pattern': '.{5,}',
                                                 'title': 'Нікнейм має містити мінімум 5 символів'}),
                                      label=False)
    signup_email = forms.CharField(max_length=32, required=True,
                                   widget=forms.EmailInput(attrs={'placeholder': _('E-mail'),
                                                                  'pattern': '^[\w]{1,}[\w.+-]{0,}@[\w-]{2,}([.][a-zA-Z]{2,}|[.][\w-]{2,}[.][a-zA-Z]{2,})$'}),
                                   label=False)
    signup_first_name = forms.CharField(max_length=30, required=True,
                                        widget=forms.TextInput(attrs={'placeholder': _("Ім'я"),
                                                                      'pattern': "([A-Za-z-'\s]+){2,30}"}),
                                        label=False)
    signup_last_name = forms.CharField(max_length=30, required=True,
                                       widget=forms.TextInput(attrs={'placeholder': _('Прізвище'),
                                                                     'pattern': "([A-Za-z-'\s]+){2,30}"}),
                                       label=False)
    phone_number = forms.CharField(max_length=16, required=True,
                                   widget=PhoneNumberPrefixWidget(attrs={'placeholder': _('Номер телефону'),
                                                                         'class': 'resizeselect',
                                                                         'pattern': "^([0-9]){7,13}$"}),
                                   label=False)
    signup_password = forms.CharField(min_length=6, max_length=32, required=True,
                                      widget=forms.PasswordInput(attrs={'placeholder': _('Пароль'),
                                                                        'pattern': '^(?=.*[A-Za-z$@$!%*#?&])(?=.*\d)[A-Za-z\d$@$!%*#?&]{6,31}$',
                                                                        'title': _(
                                                                            'Пароль має містити 6 символів та хоча б одну букву та цифру'),
                                                                        'data-expect-similar': 'password'}),
                                      label=False)
    signup_confirm_password = forms.CharField(max_length=32, required=True,
                                              widget=forms.PasswordInput(
                                                  attrs={'placeholder': _('Підтвердіть пароль'),
                                                         'title': _("Паролі мають бути однаковими"),
                                                         'data-check-similarity': 'true',
                                                         'data-expect-similar': 'password'}),
                                              label=False)

    def clean(self):
        form_data = self.cleaned_data
        username = self.cleaned_data.get("signup_username")
        email = self.cleaned_data.get("signup_email")
        password = self.cleaned_data.get("signup_password")
        confirm_password = self.cleaned_data.get("signup_confirm_password")
        phone_number = self.cleaned_data.get("phone_number")
        if password:
            validate_password(password)
        if username:
            ASCIIUsernameValidator()(username)
        if email:
            validate_email(email)
        if phone_number:
            validate_international_phonenumber(phone_number)
        if password != confirm_password:
            raise forms.ValidationError(_("Паролі не співпадають"))
        if not self.cleaned_data.get('signup_username', None):
            self._errors["signup_username"] = self.error_class(self._errors["signup_username"])
        return form_data

src/sc_auth/views.py
import json

from django.contrib.auth import get_user_model, authenticate, login
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect
from django.utils.translation import ugettext as _
from django.views.generic.edit import BaseFormView

from sc_auth.forms import LoginForm, SignUpForm
from sc_core.utils import SubmitCSFRProtectMixin

from sc_auth.services.UserService import is_user_exist

User = get_user_model()


# logger = logging.getLogger('sc_auth')


class LoginView(SubmitCSFRProtectMixin, BaseFormView):
    form_class = LoginForm

    def form_valid(self, form):
        try:
            login_username = form.cleaned_data['login_username']
            password = form.cleaned_data['login_password']
            if login_username and password:
                user = authenticate(request=self.request, username=login_username, password=password)
                if not user:
                    raise ValidationError(_("Користувача з таким логіном не існує"))
                if not user.is_active:
                    raise (_("User is not active. Activate letter sent"))
                login(self.request, user)
                return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))
        except ValidationError as e:
            for msg in e.messages:
                messages.error(self.request, msg)
            return HttpResponseRedirect(reverse('pages-root'))
        except Exception as e:
            messages.error(self.request, e)
            return HttpResponseRedirect(reverse('pages-root'))

    def post(self, request, *args, **kwargs):
        self.kwargs = kwargs
        return super(LoginView, self).post(request, *args, **kwargs)


def get(self, request, *args, **kwargs):
    return HttpResponseRedirect(reverse('pages-root'))


class SignUpView(SubmitCSFRProtectMixin, BaseFormView):
    form_class = SignUpForm

    def form_valid(self, form):
        try:
            email = form.cleaned_data['signup_email']
            password = form.cleaned_data['signup_password']
            username = form.cleaned_data['signup_username']
            first_name = form.cleaned_data['signup_first_name']
            last_name = form.cleaned_data['signup_last_name']
            phone_number = form.cleaned_data['phone_number']
            user_exist, result = is_user_exist(email=email, username=username)
            if user_exist:
                messages.error(self.request, result)
                return HttpResponseRedirect(reverse('pages-root'))
            user = User.objects.create(email=email,
                                       password=password,
                                       username=username,
                                       phone_number=phone_number,
                                       first_name=first_name,
                                       last_name=last_name,
                                       is_active=True)
            user.is_active = True
            user.save()
            login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
            return HttpResponseRedirect(reverse('pages-root'))
        except ValidationError as e:
            for msg in e.messages:
                messages.error(self.request, msg)
            return HttpResponseRedirect(reverse('pages-root'))
        except Exception as e:
            messages.error(self.request, e)
            return HttpResponseRedirect(reverse('pages-root'))

    def render_to_response(self, context):
        for key, error in context.get('form').errors.items():
            if key == "__all__":
                messages.error(self.request, error)
            else:
                messages.error(self.request, "%s:%s" % (key, error))
        return HttpResponseRedirect(reverse('pages-root'))

    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse('pages-root'))

src/sc_auth/templates/sc_auth/modals/auth_modal.html
<div class="modal fade" id="signIn" tabindex="-1" role="dialog" aria-labelledby="signIn" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="container">
                    <div class="frame">
                        <div class="nav">
                            <ul class="links">
                                <li class="signin-active"><a class="btn">Логін</a></li>
                                <li class="signup-inactive"><a class="btn">Реєстрація</a></li>
                            </ul>
                        </div>
                        <div ng-app ng-init="checked = false">
                            <form class="form-signin" action="{% url "sc_auth:login" %}" method="POST" name="form">
                                {% csrf_token %}

                                <label for="username">Логін</label>
                                {{ login_form.login_username }}
                                <label for="password">Пароль</label>
                                {{ login_form.login_password }}

                                <div class="btn-animate">
                                    <button class="btn-signin-custom" type="submit">Увійти</button>
                                </div>
                            </form>

                            <form class="form-signup" action="{% url "sc_auth:sign_up" %}" method="POST" name="form">
                                {% csrf_token %}
                                {{ sign_up_form }}
                                <button  class="btn-signup-custom" type="submit">Зареєструватись</button>
                            </form>

                            <div class="success">

                                <div class="successtext">
                                    <p> Thanks for signing up! Check your email for confirmation.</p>
                                </div>
                            </div>
                        </div>

                    </div>

                    <a id="refresh" value="Refresh" onClick="history.go()">
                        <svg class="refreshicon" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                             width="25px" height="25px" viewBox="0 0 322.447 322.447"
                             style="enable-background:new 0 0 322.447 322.447;"
                             xml:space="preserve">
                                    <path d="M321.832,230.327c-2.133-6.565-9.184-10.154-15.75-8.025l-16.254,5.281C299.785,206.991,305,184.347,305,161.224
                                            c0-84.089-68.41-152.5-152.5-152.5C68.411,8.724,0,77.135,0,161.224s68.411,152.5,152.5,152.5c6.903,0,12.5-5.597,12.5-12.5
                                            c0-6.902-5.597-12.5-12.5-12.5c-70.304,0-127.5-57.195-127.5-127.5c0-70.304,57.196-127.5,127.5-127.5
                                            c70.305,0,127.5,57.196,127.5,127.5c0,19.372-4.371,38.337-12.723,55.568l-5.553-17.096c-2.133-6.564-9.186-10.156-15.75-8.025
                                            c-6.566,2.134-10.16,9.186-8.027,15.751l14.74,45.368c1.715,5.283,6.615,8.642,11.885,8.642c1.279,0,2.582-0.198,3.865-0.614
                                            l45.369-14.738C320.371,243.946,323.965,236.895,321.832,230.327z"/>
                                </svg>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>