src/sc_auth/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import LogoutView

from sc_auth.views import LoginView, SignUpView


urlpatterns = [
    url(r'^login', LoginView.as_view(), name='login'),
    url(r'^sign_up$', SignUpView.as_view(), name='sign_up'),
    url(r'^logout', LogoutView.as_view(), name='logout'),
]

src/sc_server/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cms.urls')),
    url(r'^auth/', include(('sc_auth.urls', 'sc_auth'), namespace="sc_auth")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# urlpatterns = [
#     path(r'admin/', admin.site.urls),
#     path(r'', include('cms.urls')),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

src/sc_core/models.py
from django.db import models

# Create your models here.

src/sc_core/views.py
from django.shortcuts import render

# Create your views here.

src/sc_core/templates/sc_core/base.html
{% load cms_tags sekizai_tags static core_extras %}
<!DOCTYPE html>
<html>
<head>
    {% render_block "css" %}
    {% if not meta_title %}
        <title>{% page_attribute "page_title" %}</title>
    {% else %}
        <title>{{ meta_title }}</title>
    {% endif %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/angular.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>

{#  #}{% cms_toolbar %}
{% render_block "js" %}

{% url "clubs:ObjectsList" as objects_list_url %}
{% url "news:NewsList" as news_list_url %}
{% page_url request.current_page as this_url %}
{% url 'pages-root' as home_url %}

<header class="w-100 {% if this_url != home_url %} dark {% endif %} {% if request.user.is_superuser %} authenticated_header {% endif %}"
        id="header">
    <nav class="navbar navbar-expand-lg ">
        <a class="navbar-brand" href="{{ home_url }}">KSU SPORT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if objects_list_url %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ objects_list_url }}">Sport objects</a>
                    </li>
                {% endif %}
                {% if news_list_url %}
                    <li class="nav-item">
                        <a class="nav-link " href="{{ news_list_url }}">News</a>
                    </li>
                {% endif %}
            </ul>
            <div></div>
            <div>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'sc_auth:logout' %}?next={{ request.path }}">
                        <p class="btn btn-main-yellow">Вийти з аккаунту {{ request.user.username }}</p>
                    </a>
                {% else %}
                    <button type="button" class="btn btn-main-yellow" data-toggle="modal" data-target="#signIn">
                        Реєстрація/Увійти
                    </button>

                {% endif %}
            </div>

        </div>
    </nav>
</header>
<main>

    {% if not request.user.is_superuser %}
        {% for message in messages %}
            <section class="container-fluid popup-section active red">
                <div class="row justify-content-between mx-0 ">
                    <div class="wrapper-popup-section">
                        {{ message }}
                    </div>
                    <a href="#" class="btn-popup" id="btnPopup"></a>
                </div>
            </section>
        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}


    {% static_placeholder "Pre-footer" or %}
    {% endstatic_placeholder %}


</main>

<footer class="container-fluid footer-section">
    <div class="container">
        <div class="row justify-content-end">
            Copyright ©2019 ХДУ. Всi права захищенi
        </div>
    </div>
</footer>

{% show_auth_modals %}

</body>
</html>

src/sc_core/templates/sc_core/index.html
{% extends "sc_core/base.html" %}
{% load  cms_tags static %}
{% block head %}
{% endblock %}

{% block content %}
    {% static_placeholder "Home" or %}
    {% endstatic_placeholder %}
{% endblock %}